# Generated by Django 5.1.1 on 2024-09-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_roomrate_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrate',
            name='discounts',
            field=models.ManyToManyField(related_name='room_rates', to='main.discount'),
        ),
    ]
